-- ============================================================================
-- EXY — Provider reference fields (additive only)
--
-- Fixes: "invalid input syntax for type uuid: 'lst_msmi4xnlmphphhw'".
-- Provider references (Instagram shortcode, YouTube video id, Facebook video
-- id) and client-generated local ids must never touch a UUID column. This
-- migration gives them dedicated TEXT columns.
--
-- UUID columns are deliberately left untouched:
--   listings.id        uuid primary key  (generated by PostgreSQL)
--   listings.seller_id uuid references profiles(id)
--
-- Safe to run repeatedly. No column is renamed or dropped.
-- ============================================================================

alter table public.listings add column if not exists provider          text;
alter table public.listings add column if not exists provider_media_id text;
alter table public.listings add column if not exists video_url         text;
alter table public.listings add column if not exists thumbnail_url     text;
-- Client-side reference kept so an offline draft can be reconciled without
-- ever being used as a primary key.
alter table public.listings add column if not exists client_ref        text;

-- Only the providers the app can actually render.
do $$
begin
  alter table public.listings
    add constraint listings_provider_check
    check (provider is null or provider in ('instagram','facebook','youtube','tiktok','native'));
exception
  when duplicate_object then null;
  when duplicate_table then null;
end $$;

create index if not exists listings_provider_idx
  on public.listings(provider) where provider is not null;

-- Backfill from the existing `video` jsonb so older rows expose the same data.
update public.listings
   set provider          = coalesce(provider, video->>'provider'),
       provider_media_id = coalesce(provider_media_id, video->>'externalId'),
       video_url         = coalesce(video_url, video->>'url'),
       thumbnail_url     = coalesce(thumbnail_url, video->>'poster')
 where video is not null
   and (provider is null or video_url is null);

-- Guard against a retry creating a duplicate row for the same shared media.
create unique index if not exists listings_seller_media_uniq
  on public.listings(seller_id, provider, provider_media_id)
  where provider_media_id is not null;
