-- ============================================================================
-- EXY - Taxonomy seed (generated from src/data/taxonomy.ts - do not hand-edit)
-- Run AFTER 005_taxonomy.sql. Idempotent.
-- ============================================================================

insert into public.taxonomy_nodes (id, parent_id, level, name, slug, sort_order) values
  ('mob-phones','mobiles','subcategory','Mobile Phones','mob-phones',1),
  ('mob-smart','mob-phones','type','Smartphones','mob-smart',1),
  ('mob-feature','mob-phones','type','Feature Phones','mob-feature',2),
  ('mob-refurb','mob-phones','type','Refurbished Phones','mob-refurb',3),
  ('mob-tablets','mobiles','subcategory','Tablets','mob-tablets',2),
  ('mob-ipad','mob-tablets','type','iPad','mob-ipad',1),
  ('mob-android-tab','mob-tablets','type','Android Tablets','mob-android-tab',2),
  ('mob-wearables','mobiles','subcategory','Smart Watches & Wearables','mob-wearables',3),
  ('mob-accessories','mobiles','subcategory','Accessories','mob-accessories',4),
  ('mob-cases','mob-accessories','type','Cases & Covers','mob-cases',1),
  ('mob-chargers','mob-accessories','type','Chargers & Cables','mob-chargers',2),
  ('mob-powerbank','mob-accessories','type','Power Banks','mob-powerbank',3),
  ('mob-repair','mobiles','subcategory','Mobile Repair & Services','mob-repair',5),
  ('cmp-laptops','computers','subcategory','Laptops','cmp-laptops',1),
  ('cmp-mba','cmp-laptops','type','MacBook Air','cmp-mba',1),
  ('cmp-mbp','cmp-laptops','type','MacBook Pro','cmp-mbp',2),
  ('cmp-win-laptop','cmp-laptops','type','Windows Laptops','cmp-win-laptop',3),
  ('cmp-gaming-laptop','cmp-laptops','type','Gaming Laptops','cmp-gaming-laptop',4),
  ('cmp-chromebook','cmp-laptops','type','Chromebooks','cmp-chromebook',5),
  ('cmp-desktops','computers','subcategory','Desktop Computers','cmp-desktops',2),
  ('cmp-gaming-pc','cmp-desktops','type','Gaming PCs','cmp-gaming-pc',1),
  ('cmp-imac','cmp-desktops','type','iMac','cmp-imac',2),
  ('cmp-mac-mini','cmp-desktops','type','Mac Mini','cmp-mac-mini',3),
  ('cmp-mac-studio','cmp-desktops','type','Mac Studio','cmp-mac-studio',4),
  ('cmp-mac-pro','cmp-desktops','type','Mac Pro','cmp-mac-pro',5),
  ('cmp-workstation','cmp-desktops','type','Workstations','cmp-workstation',6),
  ('cmp-peripherals','computers','subcategory','Peripherals','cmp-peripherals',3),
  ('cmp-monitors','cmp-peripherals','type','Monitors','cmp-monitors',1),
  ('cmp-keyboards','cmp-peripherals','type','Keyboards','cmp-keyboards',2),
  ('cmp-mice','cmp-peripherals','type','Mice','cmp-mice',3),
  ('cmp-printers','cmp-peripherals','type','Printers','cmp-printers',4),
  ('cmp-scanners','cmp-peripherals','type','Scanners','cmp-scanners',5),
  ('cmp-webcams','cmp-peripherals','type','Webcams','cmp-webcams',6),
  ('cmp-networking','computers','subcategory','Networking','cmp-networking',4),
  ('cmp-routers','cmp-networking','type','Routers','cmp-routers',1),
  ('cmp-switches','cmp-networking','type','Network Switches','cmp-switches',2),
  ('cmp-nas','cmp-networking','type','NAS','cmp-nas',3),
  ('cmp-components','computers','subcategory','Components','cmp-components',5),
  ('cmp-ssd','cmp-components','type','SSDs','cmp-ssd',1),
  ('cmp-hdd','cmp-components','type','Hard Drives','cmp-hdd',2),
  ('cmp-ram','cmp-components','type','RAM','cmp-ram',3),
  ('cmp-cpu','cmp-components','type','Processors','cmp-cpu',4),
  ('cmp-gpu','cmp-components','type','Graphics Cards','cmp-gpu',5),
  ('cmp-mobo','cmp-components','type','Motherboards','cmp-mobo',6),
  ('cmp-battery','cmp-components','type','Laptop Batteries','cmp-battery',7),
  ('cmp-screen','cmp-components','type','Laptop Screens','cmp-screen',8),
  ('cmp-services','computers','subcategory','IT Services','cmp-services',6),
  ('cmp-repair','cmp-services','type','Computer Repair','cmp-repair',1),
  ('cmp-support','cmp-services','type','IT Support','cmp-support',2),
  ('cmp-webdev','cmp-services','type','Website Development','cmp-webdev',3),
  ('ele-tv','electronics','subcategory','TV & Video','ele-tv',1),
  ('ele-tvs','ele-tv','type','TVs','ele-tvs',1),
  ('ele-soundbar','ele-tv','type','Soundbars','ele-soundbar',2),
  ('ele-hometheatre','ele-tv','type','Home Theatres','ele-hometheatre',3),
  ('ele-projector','ele-tv','type','Projectors','ele-projector',4),
  ('ele-audio','electronics','subcategory','Audio','ele-audio',2),
  ('ele-speakers','ele-audio','type','Speakers','ele-speakers',1),
  ('ele-headphones','ele-audio','type','Headphones','ele-headphones',2),
  ('ele-earbuds','ele-audio','type','Earbuds','ele-earbuds',3),
  ('ele-cameras','electronics','subcategory','Cameras','ele-cameras',3),
  ('ele-camera','ele-cameras','type','Cameras','ele-camera',1),
  ('ele-lenses','ele-cameras','type','Lenses','ele-lenses',2),
  ('ele-drones','ele-cameras','type','Drones','ele-drones',3),
  ('ele-gaming','electronics','subcategory','Gaming Consoles','ele-gaming',4),
  ('ele-smarthome','electronics','subcategory','Smart Home Devices','ele-smarthome',5),
  ('ele-kitchen','electronics','subcategory','Kitchen Appliances','ele-kitchen',6),
  ('ele-microwave','ele-kitchen','type','Microwaves','ele-microwave',1),
  ('ele-airfryer','ele-kitchen','type','Air Fryers','ele-airfryer',2),
  ('ele-mixer','ele-kitchen','type','Mixers','ele-mixer',3),
  ('ele-coffee','ele-kitchen','type','Coffee Machines','ele-coffee',4),
  ('ele-purifier','ele-kitchen','type','Water Purifiers','ele-purifier',5),
  ('ele-large','electronics','subcategory','Large Appliances','ele-large',7),
  ('ele-ac','ele-large','type','Air Conditioners','ele-ac',1),
  ('ele-fridge','ele-large','type','Refrigerators','ele-fridge',2),
  ('ele-washing','ele-large','type','Washing Machines','ele-washing',3),
  ('ele-power','electronics','subcategory','Power & Energy','ele-power',8),
  ('ele-inverter','ele-power','type','Inverters','ele-inverter',1),
  ('ele-batteries','ele-power','type','Batteries','ele-batteries',2),
  ('ele-solar','ele-power','type','Solar Panels','ele-solar',3),
  ('ele-generator','ele-power','type','Generators','ele-generator',4),
  ('veh-cars','vehicles','subcategory','Cars','veh-cars',1),
  ('veh-hatchback','veh-cars','type','Hatchbacks','veh-hatchback',1),
  ('veh-sedan','veh-cars','type','Sedans','veh-sedan',2),
  ('veh-suv','veh-cars','type','SUVs','veh-suv',3),
  ('veh-muv','veh-cars','type','MUVs','veh-muv',4),
  ('veh-ev-car','veh-cars','type','Electric Cars','veh-ev-car',5),
  ('veh-bikes','vehicles','subcategory','Motorcycles','veh-bikes',2),
  ('veh-sports','veh-bikes','type','Sports Bikes','veh-sports',1),
  ('veh-cruiser','veh-bikes','type','Cruisers','veh-cruiser',2),
  ('veh-commuter','veh-bikes','type','Commuter Bikes','veh-commuter',3),
  ('veh-scooters','vehicles','subcategory','Scooters','veh-scooters',3),
  ('veh-petrol-scooter','veh-scooters','type','Petrol Scooters','veh-petrol-scooter',1),
  ('veh-ev-scooter','veh-scooters','type','Electric Scooters','veh-ev-scooter',2),
  ('veh-bicycles','vehicles','subcategory','Bicycles','veh-bicycles',4),
  ('veh-commercial','vehicles','subcategory','Commercial Vehicles','veh-commercial',5),
  ('veh-trucks','veh-commercial','type','Trucks','veh-trucks',1),
  ('veh-vans','veh-commercial','type','Vans','veh-vans',2),
  ('veh-buses','veh-commercial','type','Buses','veh-buses',3),
  ('veh-parts','vehicles','subcategory','Spare Parts & Accessories','veh-parts',6),
  ('veh-tyres','veh-parts','type','Tyres','veh-tyres',1),
  ('veh-batteries','veh-parts','type','Batteries','veh-batteries',2),
  ('veh-helmets','veh-parts','type','Helmets','veh-helmets',3),
  ('veh-services','vehicles','subcategory','Vehicle Services','veh-services',7),
  ('veh-rentals','vehicles','subcategory','Rentals','veh-rentals',8),
  ('prp-residential','property','subcategory','Residential','prp-residential',1),
  ('prp-house','prp-residential','type','Houses','prp-house',1),
  ('prp-apartment','prp-residential','type','Apartments','prp-apartment',2),
  ('prp-villa','prp-residential','type','Villas','prp-villa',3),
  ('prp-flat','prp-residential','type','Flats','prp-flat',4),
  ('prp-room','prp-residential','type','Rooms','prp-room',5),
  ('prp-shared','property','subcategory','PG & Hostels','prp-shared',2),
  ('prp-pg','prp-shared','type','PG','prp-pg',1),
  ('prp-hostel','prp-shared','type','Hostels','prp-hostel',2),
  ('prp-commercial','property','subcategory','Commercial','prp-commercial',3),
  ('prp-shop','prp-commercial','type','Shops','prp-shop',1),
  ('prp-office','prp-commercial','type','Offices','prp-office',2),
  ('prp-showroom','prp-commercial','type','Showrooms','prp-showroom',3),
  ('prp-warehouse','prp-commercial','type','Warehouses','prp-warehouse',4),
  ('prp-hotel','prp-commercial','type','Hotels','prp-hotel',5),
  ('prp-land','property','subcategory','Land & Plots','prp-land',4),
  ('prp-plot','prp-land','type','Plots','prp-plot',1),
  ('prp-agri-land','prp-land','type','Agricultural Land','prp-agri-land',2),
  ('prp-services','property','subcategory','Property Services','prp-services',5),
  ('hom-furniture','home','subcategory','Furniture','hom-furniture',1),
  ('hom-sofa','hom-furniture','type','Sofas','hom-sofa',1),
  ('hom-bed','hom-furniture','type','Beds & Mattresses','hom-bed',2),
  ('hom-dining','hom-furniture','type','Dining Sets','hom-dining',3),
  ('hom-wardrobe','hom-furniture','type','Wardrobes','hom-wardrobe',4),
  ('hom-office-furn','hom-furniture','type','Office Furniture','hom-office-furn',5),
  ('hom-decor','home','subcategory','Home Decor','hom-decor',2),
  ('hom-kitchenware','home','subcategory','Kitchenware','hom-kitchenware',3),
  ('hom-garden','home','subcategory','Garden & Outdoor','hom-garden',4),
  ('hom-tools','home','subcategory','Tools & DIY','hom-tools',5),
  ('hom-building','home','subcategory','Building Materials','hom-building',6),
  ('hom-bricks','hom-building','type','Bricks','hom-bricks',1),
  ('hom-cement','hom-building','type','Cement','hom-cement',2),
  ('hom-sand','hom-building','type','Sand & Aggregate','hom-sand',3),
  ('hom-roofing','hom-building','type','Roofing Sheets','hom-roofing',4),
  ('hom-timber','hom-building','type','Timber','hom-timber',5),
  ('fsh-clothing','fashion','subcategory','Clothing','fsh-clothing',1),
  ('fsh-mens','fsh-clothing','type','Men''s Clothing','fsh-mens',1),
  ('fsh-womens','fsh-clothing','type','Women''s Clothing','fsh-womens',2),
  ('fsh-kids','fsh-clothing','type','Kids'' Clothing','fsh-kids',3),
  ('fsh-suits','fsh-clothing','type','Suits & Formalwear','fsh-suits',4),
  ('fsh-footwear','fashion','subcategory','Footwear','fsh-footwear',2),
  ('fsh-sneakers','fsh-footwear','type','Sneakers','fsh-sneakers',1),
  ('fsh-formal-shoes','fsh-footwear','type','Formal Shoes','fsh-formal-shoes',2),
  ('fsh-watches','fashion','subcategory','Watches','fsh-watches',3),
  ('fsh-jewellery','fashion','subcategory','Jewellery','fsh-jewellery',4),
  ('fsh-bags','fashion','subcategory','Bags & Luggage','fsh-bags',5),
  ('fsh-beauty','fashion','subcategory','Beauty & Grooming','fsh-beauty',6),
  ('job-it','jobs','subcategory','IT & Software','job-it',1),
  ('job-engineering','jobs','subcategory','Engineering','job-engineering',2),
  ('job-construction','jobs','subcategory','Construction','job-construction',3),
  ('job-admin','jobs','subcategory','Administration','job-admin',4),
  ('job-sales','jobs','subcategory','Sales & Marketing','job-sales',5),
  ('job-retail','jobs','subcategory','Retail','job-retail',6),
  ('job-customer','jobs','subcategory','Customer Service','job-customer',7),
  ('job-bpo','jobs','subcategory','BPO & Call Centre','job-bpo',8),
  ('job-teaching','jobs','subcategory','Teaching','job-teaching',9),
  ('job-healthcare','jobs','subcategory','Healthcare','job-healthcare',10),
  ('job-hospitality','jobs','subcategory','Hospitality','job-hospitality',11),
  ('job-hotel','jobs','subcategory','Hotel & Tourism','job-hotel',12),
  ('job-driving','jobs','subcategory','Driving & Delivery','job-driving',13),
  ('job-security','jobs','subcategory','Security','job-security',14),
  ('job-accounting','jobs','subcategory','Accounting','job-accounting',15),
  ('job-legal','jobs','subcategory','Legal','job-legal',16),
  ('job-agriculture','jobs','subcategory','Agriculture','job-agriculture',17),
  ('job-manufacturing','jobs','subcategory','Manufacturing','job-manufacturing',18),
  ('job-domestic','jobs','subcategory','Domestic Help','job-domestic',19),
  ('job-beauty','jobs','subcategory','Beauty & Salon','job-beauty',20),
  ('job-media','jobs','subcategory','Media & Creative','job-media',21),
  ('job-government','jobs','subcategory','Government','job-government',22),
  ('job-ngo','jobs','subcategory','NGO & Charity','job-ngo',23),
  ('job-sports','jobs','subcategory','Sports & Fitness','job-sports',24),
  ('srv-home','services','subcategory','Home Services','srv-home',1),
  ('srv-electrician','srv-home','type','Electricians','srv-electrician',1),
  ('srv-plumber','srv-home','type','Plumbers','srv-plumber',2),
  ('srv-carpenter','srv-home','type','Carpenters','srv-carpenter',3),
  ('srv-painter','srv-home','type','Painters','srv-painter',4),
  ('srv-cleaning','srv-home','type','Cleaning','srv-cleaning',5),
  ('srv-pest','srv-home','type','Pest Control','srv-pest',6),
  ('srv-construction','services','subcategory','Construction & Repair','srv-construction',2),
  ('srv-roofing','srv-construction','type','Roofing Contractors','srv-roofing',1),
  ('srv-masonry','srv-construction','type','Masonry','srv-masonry',2),
  ('srv-transport','services','subcategory','Transport & Movers','srv-transport',3),
  ('srv-education','services','subcategory','Tutors & Education','srv-education',4),
  ('srv-events','services','subcategory','Events & Photography','srv-events',5),
  ('srv-professional','services','subcategory','Legal, Finance & Professional','srv-professional',6),
  ('srv-tailor','services','subcategory','Tailors & Alterations','srv-tailor',7),
  ('biz-forsale','business','subcategory','Businesses for Sale','biz-forsale',1),
  ('biz-machinery','business','subcategory','Industrial Machinery','biz-machinery',2),
  ('biz-fixtures','business','subcategory','Store Fixtures','biz-fixtures',3),
  ('biz-restaurant','business','subcategory','Restaurant Supplies','biz-restaurant',4),
  ('biz-office','business','subcategory','Office Equipment','biz-office',5),
  ('biz-wholesale','business','subcategory','Wholesale & Bulk','biz-wholesale',6),
  ('lei-books','leisure','subcategory','Books & Magazines','lei-books',1),
  ('lei-sports','leisure','subcategory','Sports Equipment','lei-sports',2),
  ('lei-fitness','leisure','subcategory','Gym & Fitness','lei-fitness',3),
  ('lei-music','leisure','subcategory','Musical Instruments','lei-music',4),
  ('lei-games','leisure','subcategory','Games & Toys','lei-games',5),
  ('lei-collectibles','leisure','subcategory','Art & Collectibles','lei-collectibles',6),
  ('lei-travel','leisure','subcategory','Travel & Outdoor Gear','lei-travel',7),
  ('agr-pets','agri','subcategory','Pets','agr-pets',1),
  ('agr-petsupplies','agri','subcategory','Pet Supplies','agr-petsupplies',2),
  ('agr-livestock','agri','subcategory','Livestock','agr-livestock',3),
  ('agr-produce','agri','subcategory','Farm Produce','agr-produce',4),
  ('agr-seeds','agri','subcategory','Seeds & Plants','agr-seeds',5),
  ('agr-equipment','agri','subcategory','Farm Equipment','agr-equipment',6),
  ('agr-organic','agri','subcategory','Organic Foods','agr-organic',7)
on conflict (id) do update set name = excluded.name, parent_id = excluded.parent_id, sort_order = excluded.sort_order;

insert into public.taxonomy_attributes (id, node_id, key, label, input_type, options, unit, required, filterable, sort_order) values
  ('mobiles__condition','mobiles','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('mobiles__brand','mobiles','brand','Brand','select','["Apple","Samsung","Xiaomi","OnePlus","Realme","Vivo","Oppo","Google","Motorola","Nothing","Other"]'::jsonb,null,false,true,1),
  ('mobiles__storage','mobiles','storage','Storage','select','["32GB","64GB","128GB","256GB","512GB","1TB"]'::jsonb,null,false,true,2),
  ('mobiles__ram','mobiles','ram','RAM','select','["2GB","4GB","6GB","8GB","12GB","16GB"]'::jsonb,null,false,true,3),
  ('mobiles__warranty','mobiles','warranty','Under warranty','boolean','[]'::jsonb,null,false,true,4),
  ('computers__condition','computers','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('computers__ram','computers','ram','RAM','select','["4GB","8GB","16GB","32GB","64GB","128GB"]'::jsonb,null,false,true,1),
  ('computers__storage','computers','storage','Storage','select','["128GB SSD","256GB SSD","512GB SSD","1TB SSD","2TB SSD","1TB HDD","2TB HDD"]'::jsonb,null,false,true,2),
  ('computers__processor','computers','processor','Processor','select','["Intel i3","Intel i5","Intel i7","Intel i9","AMD Ryzen 3","AMD Ryzen 5","AMD Ryzen 7","AMD Ryzen 9","Apple M1","Apple M2","Apple M3","Apple M4","Other"]'::jsonb,null,false,true,3),
  ('computers__os','computers','os','Operating system','select','["Windows 11","Windows 10","macOS","ChromeOS","Linux","None"]'::jsonb,null,false,true,4),
  ('computers__screen_size','computers','screen_size','Screen size','number','[]'::jsonb,'inch',false,true,5),
  ('computers__graphics','computers','graphics','Graphics card','text','[]'::jsonb,null,false,true,6),
  ('electronics__condition','electronics','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('electronics__brand','electronics','brand','Brand','text','[]'::jsonb,null,false,true,1),
  ('electronics__warranty','electronics','warranty','Under warranty','boolean','[]'::jsonb,null,false,true,2),
  ('electronics__energy_rating','electronics','energy_rating','Energy rating','select','["5 Star","4 Star","3 Star","2 Star","1 Star"]'::jsonb,null,false,true,3),
  ('vehicles__brand','vehicles','brand','Brand','text','[]'::jsonb,null,true,true,0),
  ('vehicles__model','vehicles','model','Model','text','[]'::jsonb,null,false,true,1),
  ('vehicles__year','vehicles','year','Year','number','[]'::jsonb,null,false,true,2),
  ('vehicles__mileage','vehicles','mileage','Mileage','number','[]'::jsonb,'km',false,true,3),
  ('vehicles__fuel','vehicles','fuel','Fuel type','select','["Petrol","Diesel","CNG","Electric","Hybrid","LPG"]'::jsonb,null,false,true,4),
  ('vehicles__transmission','vehicles','transmission','Transmission','select','["Manual","Automatic","AMT","CVT","DCT"]'::jsonb,null,false,true,5),
  ('vehicles__ownership','vehicles','ownership','Ownership','select','["1st owner","2nd owner","3rd owner","4th or more"]'::jsonb,null,false,true,6),
  ('vehicles__registration','vehicles','registration','Registration location','text','[]'::jsonb,null,false,true,7),
  ('property__listing_type','property','listing_type','Sale or rent','select','["For sale","For rent","PG / Shared"]'::jsonb,null,true,true,0),
  ('property__bedrooms','property','bedrooms','Bedrooms','select','["1","2","3","4","5+"]'::jsonb,null,false,true,1),
  ('property__bathrooms','property','bathrooms','Bathrooms','select','["1","2","3","4+"]'::jsonb,null,false,true,2),
  ('property__area','property','area','Area','number','[]'::jsonb,'sq ft',false,true,3),
  ('property__furnishing','property','furnishing','Furnishing','select','["Unfurnished","Semi-furnished","Fully furnished"]'::jsonb,null,false,true,4),
  ('property__parking','property','parking','Parking','select','["None","1","2","3+"]'::jsonb,null,false,true,5),
  ('property__floor','property','floor','Floor','text','[]'::jsonb,null,false,true,6),
  ('home__condition','home','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('home__material','home','material','Material','text','[]'::jsonb,null,false,true,1),
  ('home__assembly','home','assembly','Assembly required','boolean','[]'::jsonb,null,false,true,2),
  ('fashion__condition','fashion','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('fashion__size','fashion','size','Size','text','[]'::jsonb,null,false,true,1),
  ('fashion__gender','fashion','gender','For','select','["Men","Women","Unisex","Kids"]'::jsonb,null,false,true,2),
  ('fashion__brand','fashion','brand','Brand','text','[]'::jsonb,null,false,true,3),
  ('jobs__employment_type','jobs','employment_type','Employment type','select','["Full-time","Part-time","Casual","Temporary","Contract","Internship","Freelance"]'::jsonb,null,true,true,0),
  ('jobs__work_mode','jobs','work_mode','Work mode','select','["On-site","Remote","Hybrid","Work from home"]'::jsonb,null,false,true,1),
  ('jobs__salary_type','jobs','salary_type','Salary type','select','["Monthly","Daily wage","Hourly","Commission","Per project","Negotiable"]'::jsonb,null,false,true,2),
  ('jobs__salary_min','jobs','salary_min','Minimum salary','number','[]'::jsonb,'₹',false,true,3),
  ('jobs__salary_max','jobs','salary_max','Maximum salary','number','[]'::jsonb,'₹',false,true,4),
  ('jobs__experience','jobs','experience','Experience level','select','["Fresher","0-1 years","1-3 years","3-5 years","5-10 years","10+ years"]'::jsonb,null,false,true,5),
  ('jobs__education','jobs','education','Education required','select','["None","10th","12th","Diploma","Graduate","Post-graduate","Doctorate"]'::jsonb,null,false,true,6),
  ('jobs__working_hours','jobs','working_hours','Working hours','text','[]'::jsonb,null,false,true,7),
  ('jobs__vacancies','jobs','vacancies','Number of vacancies','number','[]'::jsonb,null,false,true,8),
  ('jobs__application_method','jobs','application_method','How to apply','select','["In-app message","Phone call","Email","Walk-in"]'::jsonb,null,false,true,9),
  ('jobs__closing_date','jobs','closing_date','Closing date','text','[]'::jsonb,null,false,true,10),
  ('services__service_type','services','service_type','Service type','text','[]'::jsonb,null,false,true,0),
  ('services__service_area','services','service_area','Service area','text','[]'::jsonb,null,false,true,1),
  ('services__availability','services','availability','Availability','select','["Weekdays","Weekends","All week","24x7","By appointment"]'::jsonb,null,false,true,2),
  ('services__pricing_method','services','pricing_method','Pricing method','select','["Fixed","Hourly","Per visit","Per project","Quote on request"]'::jsonb,null,false,true,3),
  ('business__condition','business','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('business__capacity','business','capacity','Capacity / output','text','[]'::jsonb,null,false,true,1),
  ('business__power','business','power','Power requirement','text','[]'::jsonb,null,false,true,2),
  ('leisure__condition','leisure','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('leisure__brand','leisure','brand','Brand','text','[]'::jsonb,null,false,true,1),
  ('agri__quantity','agri','quantity','Quantity','number','[]'::jsonb,null,false,true,0),
  ('agri__organic','agri','organic','Organic','boolean','[]'::jsonb,null,false,true,1)
on conflict (id) do update set label = excluded.label, options = excluded.options, input_type = excluded.input_type;
