-- ============================================================================
-- EXY - Taxonomy seed v2 (regenerated from src/data/taxonomy.ts)
-- 14 main categories. Run AFTER 005_taxonomy.sql. Idempotent.
-- ============================================================================

insert into public.taxonomy_nodes (id, parent_id, level, name, slug, sort_order) values
  ('electronics',null,'category','Electronics, Computers & Technology','electronics',0),
  ('ele-mobile-phones','electronics','subcategory','Mobile Phones','ele-mobile-phones',0),
  ('ele-smartphones','electronics','subcategory','Smartphones','ele-smartphones',0),
  ('ele-tablets','electronics','subcategory','Tablets','ele-tablets',0),
  ('ele-laptops','electronics','subcategory','Laptops','ele-laptops',0),
  ('ele-macbooks','electronics','subcategory','MacBooks','ele-macbooks',0),
  ('ele-desktops','electronics','subcategory','Desktop Computers','ele-desktops',0),
  ('ele-gaming-pcs','electronics','subcategory','Gaming PCs','ele-gaming-pcs',0),
  ('ele-monitors','electronics','subcategory','Monitors','ele-monitors',0),
  ('ele-accessories','electronics','subcategory','Computer Accessories','ele-accessories',0),
  ('ele-keyboards','electronics','subcategory','Keyboards','ele-keyboards',0),
  ('ele-mice','electronics','subcategory','Mice','ele-mice',0),
  ('ele-webcams','electronics','subcategory','Webcams','ele-webcams',0),
  ('ele-printers','electronics','subcategory','Printers & Scanners','ele-printers',0),
  ('ele-networking','electronics','subcategory','Routers & Networking','ele-networking',0),
  ('ele-components','electronics','subcategory','Computer Components','ele-components',0),
  ('ele-cpus','ele-components','type','CPUs','ele-cpus',0),
  ('ele-gpus','ele-components','type','GPUs','ele-gpus',0),
  ('ele-ram','ele-components','type','RAM','ele-ram',0),
  ('ele-motherboards','ele-components','type','Motherboards','ele-motherboards',0),
  ('ele-storage-drives','ele-components','type','Storage Drives','ele-storage-drives',0),
  ('ele-psu','ele-components','type','Power Supplies','ele-psu',0),
  ('ele-consoles','electronics','subcategory','Gaming Consoles','ele-consoles',0),
  ('ele-gaming-acc','electronics','subcategory','Gaming Accessories','ele-gaming-acc',0),
  ('ele-tvs','electronics','subcategory','Televisions','ele-tvs',0),
  ('ele-cameras','electronics','subcategory','Cameras','ele-cameras',0),
  ('ele-lenses','electronics','subcategory','Lenses','ele-lenses',0),
  ('ele-audio','electronics','subcategory','Audio Equipment','ele-audio',0),
  ('ele-headphones','electronics','subcategory','Headphones & Earbuds','ele-headphones',0),
  ('ele-speakers','electronics','subcategory','Speakers','ele-speakers',0),
  ('ele-smartwatches','electronics','subcategory','Smartwatches','ele-smartwatches',0),
  ('ele-wearables','electronics','subcategory','Wearables','ele-wearables',0),
  ('ele-cables','electronics','subcategory','Cables & Chargers','ele-cables',0),
  ('ele-software','electronics','subcategory','Software','ele-software',0),
  ('ele-it-services','electronics','subcategory','IT Services','ele-it-services',0),
  ('ele-repairs','electronics','subcategory','Repairs & Technical Support','ele-repairs',0),
  ('vehicles',null,'category','Vehicles','vehicles',0),
  ('veh-cars','vehicles','subcategory','Cars','veh-cars',0),
  ('veh-motorcycles','vehicles','subcategory','Motorcycles','veh-motorcycles',0),
  ('veh-scooters','vehicles','subcategory','Scooters','veh-scooters',0),
  ('veh-bicycles','vehicles','subcategory','Bicycles','veh-bicycles',0),
  ('veh-ev','vehicles','subcategory','Electric Vehicles','veh-ev',0),
  ('veh-trucks','vehicles','subcategory','Trucks','veh-trucks',0),
  ('veh-vans','vehicles','subcategory','Vans','veh-vans',0),
  ('veh-commercial','vehicles','subcategory','Commercial Vehicles','veh-commercial',0),
  ('veh-auto-parts','vehicles','subcategory','Auto Parts','veh-auto-parts',0),
  ('veh-bike-parts','vehicles','subcategory','Motorcycle Parts','veh-bike-parts',0),
  ('veh-tyres','vehicles','subcategory','Tyres & Wheels','veh-tyres',0),
  ('veh-acc','vehicles','subcategory','Vehicle Accessories','veh-acc',0),
  ('veh-services','vehicles','subcategory','Vehicle Services','veh-services',0),
  ('veh-rentals','vehicles','subcategory','Car Rentals','veh-rentals',0),
  ('veh-finance','vehicles','subcategory','Vehicle Finance','veh-finance',0),
  ('property',null,'category','Property & Real Estate','property',0),
  ('prp-house-sale','property','subcategory','Houses for Sale','prp-house-sale',0),
  ('prp-apt-sale','property','subcategory','Apartments for Sale','prp-apt-sale',0),
  ('prp-house-rent','property','subcategory','Houses for Rent','prp-house-rent',0),
  ('prp-apt-rent','property','subcategory','Apartments for Rent','prp-apt-rent',0),
  ('prp-rooms','property','subcategory','Rooms & Flatmates','prp-rooms',0),
  ('prp-land','property','subcategory','Land & Plots','prp-land',0),
  ('prp-commercial','property','subcategory','Commercial Property','prp-commercial',0),
  ('prp-shops','property','subcategory','Shops & Offices','prp-shops',0),
  ('prp-warehouses','property','subcategory','Warehouses','prp-warehouses',0),
  ('prp-industrial','property','subcategory','Industrial Property','prp-industrial',0),
  ('prp-hostels','property','subcategory','Hostels & PG','prp-hostels',0),
  ('prp-vacation','property','subcategory','Vacation Rentals','prp-vacation',0),
  ('prp-services','property','subcategory','Property Services','prp-services',0),
  ('prp-management','property','subcategory','Property Management','prp-management',0),
  ('home',null,'category','Home, Furniture & Garden','home',0),
  ('hom-sofas','home','subcategory','Sofas','hom-sofas',0),
  ('hom-beds','home','subcategory','Beds & Mattresses','hom-beds',0),
  ('hom-tables','home','subcategory','Tables & Chairs','hom-tables',0),
  ('hom-wardrobes','home','subcategory','Wardrobes','hom-wardrobes',0),
  ('hom-kitchen-furn','home','subcategory','Kitchen Furniture','hom-kitchen-furn',0),
  ('hom-office-furn','home','subcategory','Office Furniture','hom-office-furn',0),
  ('hom-decor','home','subcategory','Home Decor','hom-decor',0),
  ('hom-lighting','home','subcategory','Lighting','hom-lighting',0),
  ('hom-curtains','home','subcategory','Curtains & Blinds','hom-curtains',0),
  ('hom-appliances','home','subcategory','Appliances','hom-appliances',0),
  ('hom-fridge','hom-appliances','type','Refrigerators','hom-fridge',0),
  ('hom-washing','hom-appliances','type','Washing Machines','hom-washing',0),
  ('hom-ac','hom-appliances','type','Air Conditioners','hom-ac',0),
  ('hom-coolers','hom-appliances','type','Coolers','hom-coolers',0),
  ('hom-fans','hom-appliances','type','Fans','hom-fans',0),
  ('hom-microwave','hom-appliances','type','Microwaves','hom-microwave',0),
  ('hom-oven','hom-appliances','type','Ovens','hom-oven',0),
  ('hom-mixer','hom-appliances','type','Mixers & Grinders','hom-mixer',0),
  ('hom-coffee','hom-appliances','type','Coffee Machines','hom-coffee',0),
  ('hom-purifier','hom-appliances','type','Water Purifiers','hom-purifier',0),
  ('hom-vacuum','hom-appliances','type','Vacuum Cleaners','hom-vacuum',0),
  ('hom-geyser','hom-appliances','type','Geysers','hom-geyser',0),
  ('hom-iron','hom-appliances','type','Irons','hom-iron',0),
  ('hom-small-app','hom-appliances','type','Small Appliances','hom-small-app',0),
  ('hom-garden','home','subcategory','Gardening Equipment','hom-garden',0),
  ('hom-plants','home','subcategory','Plants','hom-plants',0),
  ('hom-tools','home','subcategory','Tools','hom-tools',0),
  ('hom-improvement','home','subcategory','Home Improvement Materials','hom-improvement',0),
  ('hom-cleaning','home','subcategory','Cleaning Equipment','hom-cleaning',0),
  ('fashion',null,'category','Fashion & Personal Items','fashion',0),
  ('fsh-mens','fashion','subcategory','Men''s Clothing','fsh-mens',0),
  ('fsh-womens','fashion','subcategory','Women''s Clothing','fsh-womens',0),
  ('fsh-kids','fashion','subcategory','Children''s Clothing','fsh-kids',0),
  ('fsh-shoes','fashion','subcategory','Shoes','fsh-shoes',0),
  ('fsh-bags','fashion','subcategory','Bags','fsh-bags',0),
  ('fsh-watches','fashion','subcategory','Watches','fsh-watches',0),
  ('fsh-jewellery','fashion','subcategory','Jewellery','fsh-jewellery',0),
  ('fsh-beauty','fashion','subcategory','Beauty Products','fsh-beauty',0),
  ('fsh-cosmetics','fashion','subcategory','Cosmetics','fsh-cosmetics',0),
  ('fsh-personal-care','fashion','subcategory','Personal Care','fsh-personal-care',0),
  ('fsh-accessories','fashion','subcategory','Accessories','fsh-accessories',0),
  ('fsh-traditional','fashion','subcategory','Traditional Clothing','fsh-traditional',0),
  ('fsh-wedding','fashion','subcategory','Wedding Clothing','fsh-wedding',0),
  ('fsh-sportswear','fashion','subcategory','Sportswear','fsh-sportswear',0),
  ('fsh-services','fashion','subcategory','Fashion Services','fsh-services',0),
  ('jobs',null,'category','Jobs & Employment','jobs',0),
  ('job-full-time','jobs','subcategory','Full-Time Jobs','job-full-time',0),
  ('job-part-time','jobs','subcategory','Part-Time Jobs','job-part-time',0),
  ('job-casual','jobs','subcategory','Casual Jobs','job-casual',0),
  ('job-contract','jobs','subcategory','Contract Jobs','job-contract',0),
  ('job-temporary','jobs','subcategory','Temporary Jobs','job-temporary',0),
  ('job-work-home','jobs','subcategory','Work From Home','job-work-home',0),
  ('job-remote','jobs','subcategory','Remote Jobs','job-remote',0),
  ('job-internship','jobs','subcategory','Internships','job-internship',0),
  ('job-freelance','jobs','subcategory','Freelance Work','job-freelance',0),
  ('job-commission','jobs','subcategory','Commission-Based Work','job-commission',0),
  ('job-delivery','jobs','subcategory','Delivery Jobs','job-delivery',0),
  ('job-driver','jobs','subcategory','Driver Jobs','job-driver',0),
  ('job-sales','jobs','subcategory','Sales Jobs','job-sales',0),
  ('job-marketing','jobs','subcategory','Marketing Jobs','job-marketing',0),
  ('job-office','jobs','subcategory','Office Jobs','job-office',0),
  ('job-customer-svc','jobs','subcategory','Customer Service','job-customer-svc',0),
  ('job-it','jobs','subcategory','IT & Software Jobs','job-it',0),
  ('job-construction','jobs','subcategory','Construction Jobs','job-construction',0),
  ('job-hospitality','jobs','subcategory','Hospitality Jobs','job-hospitality',0),
  ('job-healthcare','jobs','subcategory','Healthcare Jobs','job-healthcare',0),
  ('job-education','jobs','subcategory','Education Jobs','job-education',0),
  ('job-domestic','jobs','subcategory','Domestic Help','job-domestic',0),
  ('job-security','jobs','subcategory','Security Jobs','job-security',0),
  ('job-skilled','jobs','subcategory','Skilled Trades','job-skilled',0),
  ('services',null,'category','Services','services',0),
  ('srv-home','services','subcategory','Home Services','srv-home',0),
  ('srv-cleaning','srv-home','type','Cleaning','srv-cleaning',0),
  ('srv-plumbing','srv-home','type','Plumbing','srv-plumbing',0),
  ('srv-electrical','srv-home','type','Electrical','srv-electrical',0),
  ('srv-painting','srv-home','type','Painting','srv-painting',0),
  ('srv-carpentry','srv-home','type','Carpentry','srv-carpentry',0),
  ('srv-construction','srv-home','type','Construction','srv-construction',0),
  ('srv-moving','srv-home','type','Moving & Transport','srv-moving',0),
  ('srv-repair','services','subcategory','Repair Services','srv-repair',0),
  ('srv-computer','services','subcategory','Computer Services','srv-computer',0),
  ('srv-phone-repair','services','subcategory','Phone Repair','srv-phone-repair',0),
  ('srv-vehicle','services','subcategory','Vehicle Services','srv-vehicle',0),
  ('srv-photography','services','subcategory','Photography','srv-photography',0),
  ('srv-video','services','subcategory','Video Production','srv-video',0),
  ('srv-design','services','subcategory','Design Services','srv-design',0),
  ('srv-marketing','services','subcategory','Marketing Services','srv-marketing',0),
  ('srv-legal','services','subcategory','Legal Services','srv-legal',0),
  ('srv-accounting','services','subcategory','Accounting Services','srv-accounting',0),
  ('srv-education','services','subcategory','Education & Tutoring','srv-education',0),
  ('srv-childcare','services','subcategory','Childcare','srv-childcare',0),
  ('srv-beauty','services','subcategory','Beauty Services','srv-beauty',0),
  ('srv-fitness','services','subcategory','Fitness & Personal Training','srv-fitness',0),
  ('srv-events','services','subcategory','Event Services','srv-events',0),
  ('srv-catering','services','subcategory','Catering','srv-catering',0),
  ('srv-travel','services','subcategory','Travel Services','srv-travel',0),
  ('srv-business','services','subcategory','Business Services','srv-business',0),
  ('business',null,'category','Business & Industrial','business',0),
  ('biz-machinery','business','subcategory','Industrial Machinery','biz-machinery',0),
  ('biz-manufacturing','business','subcategory','Manufacturing Equipment','biz-manufacturing',0),
  ('biz-construction-eq','business','subcategory','Construction Equipment','biz-construction-eq',0),
  ('biz-agri-eq','business','subcategory','Agricultural Equipment','biz-agri-eq',0),
  ('biz-restaurant','business','subcategory','Restaurant Equipment','biz-restaurant',0),
  ('biz-shop-eq','business','subcategory','Shop Equipment','biz-shop-eq',0),
  ('biz-office-eq','business','subcategory','Office Equipment','biz-office-eq',0),
  ('biz-medical-eq','business','subcategory','Medical Equipment','biz-medical-eq',0),
  ('biz-safety','business','subcategory','Safety Equipment','biz-safety',0),
  ('biz-packaging','business','subcategory','Packaging Equipment','biz-packaging',0),
  ('biz-wholesale','business','subcategory','Wholesale Products','biz-wholesale',0),
  ('biz-opportunities','business','subcategory','Business Opportunities','biz-opportunities',0),
  ('biz-franchise','business','subcategory','Franchise Opportunities','biz-franchise',0),
  ('biz-commercial-supplies','business','subcategory','Commercial Supplies','biz-commercial-supplies',0),
  ('biz-raw-materials','business','subcategory','Raw Materials','biz-raw-materials',0),
  ('biz-import-export','business','subcategory','Import & Export Services','biz-import-export',0),
  ('appliances',null,'category','Home Appliances','appliances',0),
  ('app-fridge','appliances','subcategory','Refrigerators','app-fridge',0),
  ('app-freezer','appliances','subcategory','Freezers','app-freezer',0),
  ('app-washing','appliances','subcategory','Washing Machines','app-washing',0),
  ('app-dryer','appliances','subcategory','Dryers','app-dryer',0),
  ('app-dishwasher','appliances','subcategory','Dishwashers','app-dishwasher',0),
  ('app-microwave','appliances','subcategory','Microwaves','app-microwave',0),
  ('app-oven','appliances','subcategory','Ovens','app-oven',0),
  ('app-mixer','appliances','subcategory','Mixers & Grinders','app-mixer',0),
  ('app-coffee','appliances','subcategory','Coffee Machines','app-coffee',0),
  ('app-ac','appliances','subcategory','Air Conditioners','app-ac',0),
  ('app-purifier','appliances','subcategory','Air Purifiers','app-purifier',0),
  ('app-water-purifier','appliances','subcategory','Water Purifiers','app-water-purifier',0),
  ('app-vacuum','appliances','subcategory','Vacuum Cleaners','app-vacuum',0),
  ('app-fan','appliances','subcategory','Fans','app-fan',0),
  ('app-geyser','appliances','subcategory','Geysers','app-geyser',0),
  ('app-iron','appliances','subcategory','Irons','app-iron',0),
  ('app-small','appliances','subcategory','Small Appliances','app-small',0),
  ('leisure',null,'category','Books, Sports, Hobbies & Entertainment','leisure',0),
  ('lei-books','leisure','subcategory','Books','lei-books',0),
  ('lei-school-books','leisure','subcategory','School Books','lei-school-books',0),
  ('lei-college-books','leisure','subcategory','College Books','lei-college-books',0),
  ('lei-instruments','leisure','subcategory','Musical Instruments','lei-instruments',0),
  ('lei-sports-eq','leisure','subcategory','Sports Equipment','lei-sports-eq',0),
  ('lei-gym','leisure','subcategory','Gym Equipment','lei-gym',0),
  ('lei-outdoor','leisure','subcategory','Outdoor Activities','lei-outdoor',0),
  ('lei-toys','leisure','subcategory','Toys','lei-toys',0),
  ('lei-games','leisure','subcategory','Games','lei-games',0),
  ('lei-collectibles','leisure','subcategory','Collectibles','lei-collectibles',0),
  ('lei-art','leisure','subcategory','Art & Crafts','lei-art',0),
  ('lei-movies','leisure','subcategory','Movies & Music','lei-movies',0),
  ('lei-party','leisure','subcategory','Party Supplies','lei-party',0),
  ('lei-hobby','leisure','subcategory','Hobby Equipment','lei-hobby',0),
  ('lei-tickets','leisure','subcategory','Tickets & Events','lei-tickets',0),
  ('agri',null,'category','Pets, Animals & Agriculture','agri',0),
  ('agr-dogs','agri','subcategory','Dogs','agr-dogs',0),
  ('agr-cats','agri','subcategory','Cats','agr-cats',0),
  ('agr-birds','agri','subcategory','Birds','agr-birds',0),
  ('agr-fish','agri','subcategory','Fish','agr-fish',0),
  ('agr-pet-acc','agri','subcategory','Pet Accessories','agr-pet-acc',0),
  ('agr-pet-food','agri','subcategory','Pet Food','agr-pet-food',0),
  ('agr-livestock','agri','subcategory','Livestock','agr-livestock',0),
  ('agr-poultry','agri','subcategory','Poultry','agr-poultry',0),
  ('agr-cattle','agri','subcategory','Cattle','agr-cattle',0),
  ('agr-farm-eq','agri','subcategory','Farm Equipment','agr-farm-eq',0),
  ('agr-seeds','agri','subcategory','Seeds','agr-seeds',0),
  ('agr-plants','agri','subcategory','Plants','agr-plants',0),
  ('agr-fertiliser','agri','subcategory','Fertiliser','agr-fertiliser',0),
  ('agr-animal-feed','agri','subcategory','Animal Feed','agr-animal-feed',0),
  ('agr-agri-products','agri','subcategory','Agricultural Products','agr-agri-products',0),
  ('agr-farm-services','agri','subcategory','Farm Services','agr-farm-services',0),
  ('education',null,'category','Education & Training','education',0),
  ('edu-schools','education','subcategory','Schools','edu-schools',0),
  ('edu-colleges','education','subcategory','Colleges','edu-colleges',0),
  ('edu-coaching','education','subcategory','Coaching','edu-coaching',0),
  ('edu-online','education','subcategory','Online Courses','edu-online',0),
  ('edu-language','education','subcategory','Language Classes','edu-language',0),
  ('edu-computer-training','education','subcategory','Computer Training','edu-computer-training',0),
  ('edu-certification','education','subcategory','Professional Certifications','edu-certification',0),
  ('edu-music','education','subcategory','Music Classes','edu-music',0),
  ('edu-dance','education','subcategory','Dance Classes','edu-dance',0),
  ('edu-driving','education','subcategory','Driving Classes','edu-driving',0),
  ('edu-vocational','education','subcategory','Vocational Training','edu-vocational',0),
  ('edu-exam-prep','education','subcategory','Exam Preparation','edu-exam-prep',0),
  ('edu-tutors','education','subcategory','Tutors','edu-tutors',0),
  ('travel',null,'category','Travel, Leisure & Events','travel',0),
  ('trv-hotels','travel','subcategory','Hotels','trv-hotels',0),
  ('trv-rentals','travel','subcategory','Holiday Rentals','trv-rentals',0),
  ('trv-packages','travel','subcategory','Travel Packages','trv-packages',0),
  ('trv-flights','travel','subcategory','Flights','trv-flights',0),
  ('trv-bus','travel','subcategory','Bus Tickets','trv-bus',0),
  ('trv-event-tickets','travel','subcategory','Event Tickets','trv-event-tickets',0),
  ('trv-wedding','travel','subcategory','Wedding Services','trv-wedding',0),
  ('trv-party','travel','subcategory','Party Services','trv-party',0),
  ('trv-guides','travel','subcategory','Tour Guides','trv-guides',0),
  ('trv-equipment','travel','subcategory','Travel Equipment','trv-equipment',0),
  ('community',null,'category','Community & Miscellaneous','community',0),
  ('com-lost-found','community','subcategory','Lost & Found','com-lost-found',0),
  ('com-free','community','subcategory','Free Items','com-free',0),
  ('com-donations','community','subcategory','Donations','com-donations',0),
  ('com-announcements','community','subcategory','Announcements','com-announcements',0),
  ('com-groups','community','subcategory','Local Groups','com-groups',0),
  ('com-community-svc','community','subcategory','Community Services','com-community-svc',0),
  ('com-other','community','subcategory','Other','com-other',0)
on conflict (id) do update set name = excluded.name, parent_id = excluded.parent_id, sort_order = excluded.sort_order;

insert into public.taxonomy_attributes (id, node_id, key, label, input_type, options, unit, required, filterable, sort_order) values
  ('electronics__condition','electronics','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('electronics__brand','electronics','brand','Brand','text','[]'::jsonb,null,false,true,1),
  ('electronics__model','electronics','model','Model','text','[]'::jsonb,null,false,true,2),
  ('electronics__ram','electronics','ram','RAM','select','["2GB","4GB","8GB","16GB","32GB","64GB","128GB"]'::jsonb,null,false,true,3),
  ('electronics__storage','electronics','storage','Storage','select','["32GB","64GB","128GB","256GB","512GB","1TB","2TB"]'::jsonb,null,false,true,4),
  ('electronics__processor','electronics','processor','Processor','select','["Intel i3","Intel i5","Intel i7","Intel i9","AMD Ryzen 3","AMD Ryzen 5","AMD Ryzen 7","AMD Ryzen 9","Apple M1","Apple M2","Apple M3","Apple M4","Snapdragon","MediaTek","Other"]'::jsonb,null,false,true,5),
  ('electronics__screen_size','electronics','screen_size','Screen size','number','[]'::jsonb,'inch',false,true,6),
  ('electronics__graphics','electronics','graphics','Graphics card','text','[]'::jsonb,null,false,true,7),
  ('electronics__warranty','electronics','warranty','Under warranty','boolean','[]'::jsonb,null,false,true,8),
  ('electronics__color','electronics','color','Color','text','[]'::jsonb,null,false,true,9),
  ('vehicles__make','vehicles','make','Make','text','[]'::jsonb,null,true,true,0),
  ('vehicles__model','vehicles','model','Model','text','[]'::jsonb,null,false,true,1),
  ('vehicles__year','vehicles','year','Year','number','[]'::jsonb,null,false,true,2),
  ('vehicles__mileage','vehicles','mileage','Mileage','number','[]'::jsonb,'km',false,true,3),
  ('vehicles__fuel','vehicles','fuel','Fuel type','select','["Petrol","Diesel","CNG","Electric","Hybrid","LPG"]'::jsonb,null,false,true,4),
  ('vehicles__transmission','vehicles','transmission','Transmission','select','["Manual","Automatic","AMT","CVT","DCT"]'::jsonb,null,false,true,5),
  ('vehicles__ownership','vehicles','ownership','Ownership','select','["1st owner","2nd owner","3rd owner","4th or more"]'::jsonb,null,false,true,6),
  ('vehicles__registration','vehicles','registration','Registration location','text','[]'::jsonb,null,false,true,7),
  ('vehicles__color','vehicles','color','Color','text','[]'::jsonb,null,false,true,8),
  ('property__listing_type','property','listing_type','Sale or rent','select','["For sale","For rent","PG / Shared"]'::jsonb,null,true,true,0),
  ('property__bedrooms','property','bedrooms','Bedrooms','select','["1","2","3","4","5+"]'::jsonb,null,false,true,1),
  ('property__bathrooms','property','bathrooms','Bathrooms','select','["1","2","3","4+"]'::jsonb,null,false,true,2),
  ('property__area','property','area','Area','number','[]'::jsonb,'sq ft',false,true,3),
  ('property__furnishing','property','furnishing','Furnishing','select','["Unfurnished","Semi-furnished","Fully furnished"]'::jsonb,null,false,true,4),
  ('property__parking','property','parking','Parking','select','["None","1","2","3+"]'::jsonb,null,false,true,5),
  ('property__floor','property','floor','Floor','text','[]'::jsonb,null,false,true,6),
  ('property__facing','property','facing','Facing','text','[]'::jsonb,null,false,true,7),
  ('property__age','property','age','Property age','text','[]'::jsonb,null,false,true,8),
  ('property__owner_type','property','owner_type','Ownership','select','["Freehold","Leasepower","Power of attorney"]'::jsonb,null,false,true,9),
  ('home__condition','home','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('home__material','home','material','Material','text','[]'::jsonb,null,false,true,1),
  ('home__assembly','home','assembly','Assembly required','boolean','[]'::jsonb,null,false,true,2),
  ('fashion__condition','fashion','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('fashion__size','fashion','size','Size','text','[]'::jsonb,null,false,true,1),
  ('fashion__gender','fashion','gender','For','select','["Men","Women","Unisex","Kids","Boys","Girls"]'::jsonb,null,false,true,2),
  ('fashion__brand','fashion','brand','Brand','text','[]'::jsonb,null,false,true,3),
  ('fashion__material','fashion','material','Material','text','[]'::jsonb,null,false,true,4),
  ('jobs__employment_type','jobs','employment_type','Employment type','select','["Full-Time","Part-Time","Casual","Contract","Temporary","Internship","Freelance"]'::jsonb,null,true,true,0),
  ('jobs__work_mode','jobs','work_mode','Work mode','select','["On-site","Remote","Hybrid","Work from home"]'::jsonb,null,false,true,1),
  ('jobs__salary_type','jobs','salary_type','Payment frequency','select','["Monthly","Daily wage","Hourly","Commission","Per project","Negotiable"]'::jsonb,null,false,true,2),
  ('jobs__salary_min','jobs','salary_min','Minimum salary','number','[]'::jsonb,'₹',false,true,3),
  ('jobs__salary_max','jobs','salary_max','Maximum salary','number','[]'::jsonb,'₹',false,true,4),
  ('jobs__experience','jobs','experience','Experience level','select','["Fresher","0-1 years","1-3 years","3-5 years","5-10 years","10+ years"]'::jsonb,null,false,true,5),
  ('jobs__education','jobs','education','Education required','select','["None","10th","12th","Diploma","Graduate","Post-graduate","Doctorate"]'::jsonb,null,false,true,6),
  ('jobs__working_hours','jobs','working_hours','Working hours','text','[]'::jsonb,null,false,true,7),
  ('jobs__company','jobs','company','Company name','text','[]'::jsonb,null,false,true,8),
  ('jobs__vacancies','jobs','vacancies','Number of vacancies','number','[]'::jsonb,null,false,true,9),
  ('jobs__application_method','jobs','application_method','How to apply','select','["In-app message","Phone call","Email","Walk-in"]'::jsonb,null,false,true,10),
  ('jobs__closing_date','jobs','closing_date','Closing date','text','[]'::jsonb,null,false,true,11),
  ('jobs__benefits','jobs','benefits','Benefits','text','[]'::jsonb,null,false,true,12),
  ('services__service_type','services','service_type','Service type','text','[]'::jsonb,null,false,true,0),
  ('services__service_area','services','service_area','Service area','text','[]'::jsonb,null,false,true,1),
  ('services__availability','services','availability','Availability','select','["Weekdays","Weekends","All week","24x7","By appointment"]'::jsonb,null,false,true,2),
  ('services__pricing_method','services','pricing_method','Pricing method','select','["Fixed","Hourly","Per visit","Per project","Quote on request"]'::jsonb,null,false,true,3),
  ('services__experience_years','services','experience_years','Years of experience','number','[]'::jsonb,null,false,true,4),
  ('business__condition','business','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('business__capacity','business','capacity','Capacity / output','text','[]'::jsonb,null,false,true,1),
  ('business__power_req','business','power_req','Power requirement','text','[]'::jsonb,null,false,true,2),
  ('appliances__condition','appliances','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('appliances__brand','appliances','brand','Brand','text','[]'::jsonb,null,false,true,1),
  ('appliances__capacity','appliances','capacity','Capacity','text','[]'::jsonb,null,false,true,2),
  ('appliances__energy_rating','appliances','energy_rating','Energy rating','select','["5 Star","4 Star","3 Star","2 Star","1 Star"]'::jsonb,null,false,true,3),
  ('leisure__condition','leisure','condition','Condition','select','["New","Like new","Good","Used","For parts"]'::jsonb,null,false,true,0),
  ('leisure__genre','leisure','genre','Genre / type','text','[]'::jsonb,null,false,true,1),
  ('leisure__author_artist','leisure','author_artist','Author / artist','text','[]'::jsonb,null,false,true,2),
  ('agri__breed_type','agri','breed_type','Breed / type','text','[]'::jsonb,null,false,true,0),
  ('agri__age','agri','age','Age','text','[]'::jsonb,null,false,true,1),
  ('agri__vaccinated','agri','vaccinated','Vaccinated','boolean','[]'::jsonb,null,false,true,2),
  ('agri__quantity','agri','quantity','Quantity','number','[]'::jsonb,null,false,true,3),
  ('agri__organic','agri','organic','Organic','boolean','[]'::jsonb,null,false,true,4),
  ('education__course_type','education','course_type','Course type','select','["Online","Offline","Hybrid"]'::jsonb,null,false,true,0),
  ('education__subject','education','subject','Subject','text','[]'::jsonb,null,false,true,1),
  ('education__level','education','level','Level','select','["Beginner","Intermediate","Advanced","Professional"]'::jsonb,null,false,true,2),
  ('education__duration','education','duration','Duration','text','[]'::jsonb,null,false,true,3),
  ('education__certification','education','certification','Certification provided','boolean','[]'::jsonb,null,false,true,4),
  ('education__fees','education','fees','Fees','number','[]'::jsonb,'₹',false,true,5),
  ('travel__travel_type','travel','travel_type','Type','select','["Hotel","Rental","Package","Ticket","Service"]'::jsonb,null,false,true,0),
  ('travel__location','travel','location','Location','text','[]'::jsonb,null,false,true,1),
  ('travel__duration','travel','duration','Duration','text','[]'::jsonb,null,false,true,2),
  ('travel__price_per_night','travel','price_per_night','Price per night','number','[]'::jsonb,'₹',false,true,3),
  ('travel__amenities','travel','amenities','Amenities','text','[]'::jsonb,null,false,true,4),
  ('community__post_type','community','post_type','Post type','select','["Lost","Found","Free","Donation","Announcement","Group","Other"]'::jsonb,null,false,true,0)
on conflict (id) do update set label = excluded.label, options = excluded.options, input_type = excluded.input_type;
