-- ============================================================================
-- EXY — Comprehensive marketplace taxonomy expansion (additive only)
-- Run after 005_taxonomy.sql, 010_taxonomy_seed_v2.sql and 012_vehicle_taxonomy_expansion.sql.
-- This adds/updates taxonomy metadata only. It does not delete listings,
-- users, media, routes, UI components, or existing permissions.
-- ============================================================================

insert into public.taxonomy_nodes (id, parent_id, level, name, slug, sort_order) values
  -- Electronics / computers
  ('ele-mobile-phones','electronics','subcategory','Mobile Phones & Accessories','ele-mobile-phones',0),
  ('ele-phone-smart','ele-mobile-phones','type','Smartphones','ele-phone-smart',0),
  ('ele-phone-watch','ele-mobile-phones','type','Smartwatches & Fitness Trackers','ele-phone-watch',1),
  ('ele-phone-case','ele-mobile-phones','type','Cases, Covers & Screen Protectors','ele-phone-case',2),
  ('ele-phone-power','ele-mobile-phones','type','Chargers, Cables & Power Banks','ele-phone-power',3),
  ('ele-laptop-windows','ele-laptops','type','Windows Laptops','ele-laptop-windows',0),
  ('ele-laptop-mac','ele-laptops','type','MacBooks','ele-laptop-mac',1),
  ('ele-laptop-gaming','ele-laptops','type','Gaming Laptops','ele-laptop-gaming',2),
  ('ele-laptop-chromebook','ele-laptops','type','Chromebooks','ele-laptop-chromebook',3),
  ('ele-desktop-office','ele-desktops','type','Office & Home PCs','ele-desktop-office',0),
  ('ele-desktop-gaming','ele-desktops','type','Gaming Rigs','ele-desktop-gaming',1),
  ('ele-desktop-workstation','ele-desktops','type','Workstations & Servers','ele-desktop-workstation',2),
  ('ele-console-playstation','ele-consoles','type','PlayStation Consoles & Games','ele-console-playstation',0),
  ('ele-console-xbox','ele-consoles','type','Xbox Consoles & Games','ele-console-xbox',1),
  ('ele-console-nintendo','ele-consoles','type','Nintendo Consoles & Games','ele-console-nintendo',2),
  ('ele-console-retro','ele-consoles','type','Retro Gaming & Arcade','ele-console-retro',3),
  ('ele-tv-smart','ele-tvs','type','Smart TVs & Projectors','ele-tv-smart',0),
  ('ele-tv-sound','ele-tvs','type','Soundbars & Home Audio','ele-tv-sound',1),
  ('ele-tv-amp','ele-tvs','type','Amplifiers & Receivers','ele-tv-amp',2),
  ('ele-camera-dslr','ele-cameras','type','DSLR & Mirrorless Cameras','ele-camera-dslr',0),
  ('ele-camera-action','ele-cameras','type','Action Cameras','ele-camera-action',1),
  ('ele-camera-drone','ele-cameras','type','Drones','ele-camera-drone',2),

  -- Property, home and fashion
  ('prp-for-rent','property','subcategory','For Rent','prp-for-rent',0),
  ('prp-rent-apartment','prp-for-rent','type','Apartments & Flats','prp-rent-apartment',0),
  ('prp-rent-house','prp-for-rent','type','Houses','prp-rent-house',1),
  ('prp-rent-share','prp-for-rent','type','Room Share & Flatshare','prp-rent-share',2),
  ('prp-rent-commercial','prp-for-rent','type','Commercial Property & Offices','prp-rent-commercial',3),
  ('prp-rent-parking','prp-for-rent','type','Parking & Storage','prp-rent-parking',4),
  ('prp-for-sale','property','subcategory','For Sale','prp-for-sale',1),
  ('prp-sale-house','prp-for-sale','type','Houses','prp-sale-house',0),
  ('prp-sale-apartment','prp-for-sale','type','Apartments & Condos','prp-sale-apartment',1),
  ('prp-sale-land','prp-for-sale','type','Land & Plots','prp-sale-land',2),
  ('prp-sale-commercial','prp-for-sale','type','Commercial Real Estate','prp-sale-commercial',3),
  ('hom-furniture','home','subcategory','Furniture','hom-furniture',0),
  ('hom-furn-sofa','hom-furniture','type','Sofas, Couches & Armchairs','hom-furn-sofa',0),
  ('hom-furn-bed','hom-furniture','type','Beds, Mattresses & Bedroom Furniture','hom-furn-bed',1),
  ('hom-furn-dining','hom-furniture','type','Dining Tables & Chairs','hom-furn-dining',2),
  ('hom-furn-office','hom-furniture','type','Desks & Home Office Furniture','hom-furn-office',3),
  ('hom-furn-storage','hom-furniture','type','TV Units, Cabinets & Bookcases','hom-furn-storage',4),
  ('hom-furn-wardrobe','hom-furniture','type','Wardrobes & Drawers','hom-furn-wardrobe',5),
  ('hom-decor-collection','home','subcategory','Home Decor','hom-decor-collection',1),
  ('hom-decor-rugs','hom-decor-collection','type','Rugs, Carpets & Mats','hom-decor-rugs',0),
  ('hom-decor-art','hom-decor-collection','type','Mirrors & Wall Art','hom-decor-art',1),
  ('hom-decor-soft','hom-decor-collection','type','Curtains, Blinds & Cushions','hom-decor-soft',2),
  ('hom-decor-light','hom-decor-collection','type','Lighting, Lamps & Chandeliers','hom-decor-light',3),
  ('hom-decor-vases','hom-decor-collection','type','Candles & Vases','hom-decor-vases',4),
  ('hom-garden-outdoor','home','subcategory','Garden & Outdoor','hom-garden-outdoor',2),
  ('hom-garden-mower','hom-garden-outdoor','type','Lawn Mowers & Trimmers','hom-garden-mower',0),
  ('hom-garden-patio','hom-garden-outdoor','type','Outdoor & Patio Furniture','hom-garden-patio',1),
  ('hom-garden-bbq','hom-garden-outdoor','type','BBQs & Grills','hom-garden-bbq',2),
  ('hom-garden-plants','hom-garden-outdoor','type','Plants, Pots & Seeds','hom-garden-plants',3),
  ('hom-garden-tools','hom-garden-outdoor','type','Power Tools','hom-garden-tools',4),
  ('hom-garden-sheds','hom-garden-outdoor','type','Garden Sheds & Storage','hom-garden-sheds',5),
  ('fsh-women-dress','fsh-womens','type','Dresses & Skirts','fsh-women-dress',0),
  ('fsh-women-tops','fsh-womens','type','Tops, T-Shirts & Blouses','fsh-women-tops',1),
  ('fsh-women-jackets','fsh-womens','type','Coats, Jackets & Hoodies','fsh-women-jackets',2),
  ('fsh-women-pants','fsh-womens','type','Jeans, Pants & Leggings','fsh-women-pants',3),
  ('fsh-women-active','fsh-womens','type','Activewear & Gym Clothes','fsh-women-active',4),
  ('fsh-women-swim','fsh-womens','type','Swimwear','fsh-women-swim',5),
  ('fsh-men-shirts','fsh-mens','type','Shirts & T-Shirts','fsh-men-shirts',0),
  ('fsh-men-pants','fsh-mens','type','Pants, Jeans & Chinos','fsh-men-pants',1),
  ('fsh-men-suits','fsh-mens','type','Suits & Formal Wear','fsh-men-suits',2),
  ('fsh-men-jackets','fsh-mens','type','Coats, Jackets & Jumpers','fsh-men-jackets',3),
  ('fsh-men-active','fsh-mens','type','Activewear','fsh-men-active',4),
  ('fsh-shoe-sneaker','fsh-shoes','type','Sneakers & Athletic Shoes','fsh-shoe-sneaker',0),
  ('fsh-shoe-boots','fsh-shoes','type','Boots','fsh-shoe-boots',1),
  ('fsh-shoe-heels','fsh-shoes','type','Heels & Wedges','fsh-shoe-heels',2),
  ('fsh-shoe-sandal','fsh-shoes','type','Sandals & Slides','fsh-shoe-sandal',3),
  ('fsh-shoe-formal','fsh-shoes','type','Formal & Dress Shoes','fsh-shoe-formal',4),

  -- Jobs: sectors and employment filters remain separate attributes in the app.
  ('job-trades','jobs','subcategory','Trades & Labour','job-trades',0),
  ('job-trades-carpentry','job-trades','type','Carpentry & Joinery','job-trades-carpentry',0),
  ('job-trades-plumbing','job-trades','type','Plumbing','job-trades-plumbing',1),
  ('job-trades-construction','job-trades','type','Construction & Labouring','job-trades-construction',2),
  ('job-trades-electrical','job-trades','type','Electrical','job-trades-electrical',3),
  ('job-trades-mechanical','job-trades','type','Mechanical & Automotive','job-trades-mechanical',4),
  ('job-trades-landscaping','job-trades','type','Landscaping & Gardening','job-trades-landscaping',5),
  ('job-sales-retail','jobs','subcategory','Sales & Retail','job-sales-retail',1),
  ('job-hospitality-tourism','jobs','subcategory','Hospitality & Tourism','job-hospitality-tourism',2),
  ('job-office-support','jobs','subcategory','Admin, Office & Secretarial','job-office-support',3),
  ('job-logistics','jobs','subcategory','Transport, Logistics & Warehousing','job-logistics',4),
  ('job-health-care','jobs','subcategory','Healthcare, Nursing & Care','job-health-care',5),
  ('job-childcare-nannies','jobs','subcategory','Childcare & Nannies','job-childcare-nannies',6),
  ('job-tech-software','jobs','subcategory','IT, Tech & Software Development','job-tech-software',7),
  ('job-finance-legal','jobs','subcategory','Accounting, Finance & Legal','job-finance-legal',8),
  ('job-pr-marketing','jobs','subcategory','Marketing, Advertising & PR','job-pr-marketing',9),
  ('job-teaching','jobs','subcategory','Education & Teaching','job-teaching',10),
  ('job-cleaning-housekeeping','jobs','subcategory','Cleaning & Housekeeping','job-cleaning-housekeeping',11),
  ('job-call-centres','jobs','subcategory','Customer Service & Call Centres','job-call-centres',12),

  -- Services/community
  ('srv-local','services','subcategory','Local Services','srv-local',0),
  ('srv-handyman','srv-local','type','Handyman','srv-handyman',0),
  ('srv-mechanics','srv-local','type','Mechanics','srv-mechanics',1),
  ('srv-removals','srv-local','type','Removals','srv-removals',2),
  ('srv-tutors','srv-local','type','Tutors','srv-tutors',3),
  ('srv-classes','services','subcategory','Classes & Lessons','srv-classes',1),
  ('srv-gigs','services','subcategory','Events & Gigs','srv-gigs',2),

  -- Sports / hobbies
  ('lei-guitar','lei-instruments','type','Guitars & String Instruments','lei-guitar',0),
  ('lei-keyboards','lei-instruments','type','Keyboards & Pianos','lei-keyboards',1),
  ('lei-drums','lei-instruments','type','Drums & Percussion','lei-drums',2),
  ('lei-football','lei-sports-eq','type','Football & Soccer','lei-football',0),
  ('lei-basketball','lei-sports-eq','type','Basketball','lei-basketball',1),
  ('lei-cricket','lei-sports-eq','type','Cricket','lei-cricket',2),
  ('lei-weights','lei-gym','type','Weights & Strength Training','lei-weights',0),
  ('lei-treadmill','lei-gym','type','Treadmills & Cardio','lei-treadmill',1),
  ('lei-bands','lei-gym','type','Resistance Bands & Yoga','lei-bands',2),
  ('lei-tents','lei-outdoor','type','Tents & Shelters','lei-tents',0),
  ('lei-packs','lei-outdoor','type','Backpacks & Sleeping Bags','lei-packs',1),
  ('lei-fishing','lei-outdoor','type','Fishing Tackle & Rods','lei-fishing',2),
  ('lei-golf','lei-outdoor','type','Golf Equipment','lei-golf',3),

  -- Pets and family
  ('agr-pet-beds','agr-pet-acc','type','Pet Beds, Cages & Crates','agr-pet-beds',0),
  ('agr-pet-toys','agr-pet-acc','type','Toys, Leashes & Collars','agr-pet-toys',1),
  ('agr-aquariums','agr-pet-acc','type','Aquariums & Fish Tanks','agr-aquariums',2),
  ('family',null,'category','Family, Baby & Kids','family-baby-kids',15),
  ('fam-clothing','family','subcategory','Baby Clothing & Footwear','fam-clothing',0),
  ('fam-toys','family','subcategory','Toys & Games','fam-toys',1),
  ('fam-travel','family','subcategory','Prams, Strollers & Car Seats','fam-travel',2),
  ('fam-nursery','family','subcategory','Nursery Furniture & Bedding','fam-nursery',3),
  ('fam-feeding','family','subcategory','Feeding & Bathing Accessories','fam-feeding',4),
  ('fam-maternity','family','subcategory','Maternity & Pregnancy','fam-maternity',5)
on conflict (id) do update set
  parent_id = excluded.parent_id,
  level = excluded.level,
  name = excluded.name,
  slug = excluded.slug,
  sort_order = excluded.sort_order,
  active = true;

insert into public.taxonomy_attributes (id, node_id, key, label, input_type, options, unit, required, filterable, sort_order) values
  ('family__condition','family','condition','Condition','select','["New","Like new","Good","Used"]'::jsonb,null,false,true,0),
  ('family__age_group','family','age_group','Age group','select','["Newborn","0-2 years","3-5 years","6-9 years","10-12 years","Teens"]'::jsonb,null,false,true,1),
  ('jobs__employment_type','jobs','employment_type','Employment type','select','["Full-Time","Part-Time","Casual / Vacation","Contract / Temp","Apprenticeship","Internship","Freelance"]'::jsonb,null,true,true,0),
  ('jobs__salary_type','jobs','salary_type','Payment frequency','select','["Monthly","Daily wage","Hourly","Commission","Per project","Negotiable"]'::jsonb,null,false,true,1)
on conflict (id) do update set
  label = excluded.label,
  input_type = excluded.input_type,
  options = excluded.options,
  required = excluded.required,
  filterable = excluded.filterable,
  sort_order = excluded.sort_order;
